### ISSUE TITLE
object has no attribute 'STA_IF'

### ISSUE THREAD

**Issue by vbonilla** [tiagocoutinho/us2n#1]
Hi, I'm a newbie, just got a WiPy and want to make a serial to wifi bridge. I follow the instructions and it fails like this:

Traceback (most recent call last):
  File "<stdin>", line 15, in <module>
  File "<stdin>", line 9, in start_us2n
  File "us2n.py", line 242, in server
  File "us2n.py", line 224, in config_network
  File "us2n.py", line 166, in config_wlan
  File "us2n.py", line 175, in WLANStation
AttributeError: 'module' object has no attribute 'STA_IF'

If I use REPL, I get the following:

MicroPython v1.8.6-621-g17ee404e on 2017-05-25; WiPy with ESP32
Type "help()" for more information.
>>>
>>> import network
>>> wlan = network.WLAN(network.STA_IF)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'STA_IF'

I'm not able to find anything on the web on this issue.

Any help would be appreciated,

Victor

**Comment by tiagocoutinho** [comment]
Probably too late but here it goes:

I don't know the WiPy board. Looks like it doesn't have WLAN station capability.

* does your board come with WIFI?
* is micropython version compiled with wifi capability?

**Comment by prabhu277299** [comment]
AttributeError: 'function' object has no attribute 'STA'.
The same error for me too.
If anyone can , please help
